### ISSUE TITLE
Provide getters for the various fields on our `Elements` resource

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/sgp4#9]
As discussed on Slack, we've decided to defer adding getters to the `Elements` resource so  https://github.com/wasmerio/sgp4/pull/5 can be merged.

The `datetime` field is a `chrono::NaiveDateTime`, so we'll want to create some sort of `timestamp` record with `secs` and `nanos` fields, then add `From` implementations for converting back and forth.

**Comment by dynamite-bud** [comment]
Closed in #5
